### ISSUE TITLE
too long time to wait

### ISSUE THREAD

**Issue by ggsonic** [yu20103983/FOTS#21]
the code running ` enqueuer = GeneratorEnqueuer(generator(**kwargs), use_multiprocessing=True)
        print('Generator use 10 batches for buffering, this may take a while, you can tune this yourself.')
        enqueuer.start(max_queue_size=10, workers=num_workers)`

8 cpu all go up, keep running for several hours, but gpu usage is 0, and seems not starting training.

**Comment by ggsonic** [comment]
my error, sorry.

**Comment by 6457tang** [comment]
> my error, sorry.

what is the error? I also meet the problem.
