### ISSUE TITLE
ValueError: not enough values to unpack (expected 3, got 1)

### ISSUE THREAD

**Issue by kei6** [yu20103983/FOTS#4]
Hi @yu20103983 ,
I've faced with this issue, Can you help to fix this?
``` 
 File "/home/FOTS/multigpu_train.py", line 230, in main
    fots_testModel.detectRecg(d_images, sess=sess)
  File "/home/FOTS/FOTS/fots_testModel.py", line 257, in detectRecg
    rois_op, ws_op = RoiRotate.RoiRotate(filter_bsharedFeatures, FLAGS.features_stride)(brotateParas)
  File "/home/FOTS/FOTS/RoiRotate.py", line 50, in __call__
    outBoxes, cropBoxes, angles = rboxes
ValueError: not enough values to unpack (expected 3, got 1)
```
Thanks a lot ^^!

**Comment by yu20103983** [comment]
You must have changed something. variable rboxes come from dataset.dataReader.restore_roiRotatePara, check there first.

**Comment by kei6** [comment]
I've already checked that. I found that `dataset.dataReader.restore_roiRotatePara` works well.

Having some wrong in `brotateParas` hence the issue. I found that `brotateParas` is a nested list, and `RoiRotate.RoiRotate` cannot work with this nested list.
I've already tried to convert `brotateParas`  into a flatten list, by using:
```
        import more_itertools
        brotateParas = list(more_itertools.flatten(brotateParas))

        rois_op, ws_op = RoiRotate.RoiRotate(filter_bsharedFeatures, FLAGS.features_stride)(brotateParas)
```
but another bug comes out. Test function seems to be not working!

Could you please check it again?

Thanks in advance!

**Comment by yu20103983** [comment]
oh！ I have found this bug.I forgot to extract the nested list as a single list. You can update the modified code to solve this problem. 
Thanks, good luck!

**Comment by kei6** [comment]
Thanks @yu20103983
